# Generated by Django 4.0.6 on 2022-09-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing_Title', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Restaurant', 'Restaurant'), ('Hotel', 'Hotel'), ('café', 'café'), ('Shopping', 'Shopping'), ('Fitness', 'Fitness'), ('Education', 'Education')], max_length=50)),
                ('Keywords', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('Features', multiselectfield.db.fields.MultiSelectField(choices=[('Open Now', 'Open Now'), ('Near me', 'Near me'), ('Child Friendly', 'Child Friendly'), ('Free Parking', 'Free Parking'), ('Events', 'Events'), ('Free Wifi', 'Free Wifi')], default='teacher', max_length=61)),
                ('Gallery', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('city', models.CharField(choices=[('Sfax', 'Sfax'), ('Sousse', 'Sousse'), ('Tunis', 'Tunis'), ('Monastir', 'Monastir'), ('Hammemat', 'Hammemat'), ('Mahdia', 'Mahdia')], max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Zip_Code', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=100)),
                ('Longitude', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Facebook_Link', models.CharField(max_length=100)),
                ('Twitter_Link', models.CharField(max_length=100)),
                ('Pinterest', models.CharField(max_length=100)),
                ('avg_rating', models.FloatField(default=0, max_length=100)),
                ('post_views', models.IntegerField(blank=True, default=0, null=True)),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customers/profiles/avatars/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('message', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('email', models.TextField()),
                ('Gallery', models.ImageField(upload_to='Gallery/%y/%m/%d')),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
