# Generated by Django 4.0.6 on 2022-09-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mon', models.JSONField()),
                ('Tue', models.JSONField()),
                ('ther', models.JSONField()),
                ('wend', models.JSONField()),
                ('fird', models.JSONField()),
                ('satu', models.JSONField()),
                ('sand', models.JSONField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.listing')),
            ],
        ),
    ]
