# Generated by Django 4.0.6 on 2022-09-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='days',
        ),
    ]
