# Generated by Django 4.0.6 on 2022-09-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_person_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='Mon',
            new_name='Friday',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='Tue',
            new_name='Monday',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='fird',
            new_name='Saturday',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='sand',
            new_name='Sunday',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='satu',
            new_name='Thursday',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='ther',
            new_name='Tuesday',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='wend',
            new_name='Wednesday',
        ),
    ]
