# Generated by Django 4.0.6 on 2022-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_mon_days_friday_rename_tue_days_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Status',
            field=models.CharField(default='close', max_length=100),
        ),
    ]
